# Teste para o endpoint que adiciona um novo aluno.

POST http://localhost:5186/alunos
Content-Type: application/json

{
    "Matricula": 987,
    "Nome": "Rafael Zacharkim",
    "Materias": []
}

###

# Teste para o endpoint que obtém todos os alunos.

GET http://localhost:5186/alunos

###

# Teste para o endpoint que deleta um aluno.

DELETE http://localhost:5186/alunos/987
