// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEscolaDeIdiomas.Models;

#nullable disable

namespace ProjetoEscolaDeIdiomas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241017180327_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.AlunoMateria", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoId", "MateriaId");

                    b.HasIndex("MateriaId");

                    b.ToTable("AlunoMaterias");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.AlunoMateria", b =>
                {
                    b.HasOne("ProjetoEscolaDeIdiomas.Models.Aluno", "Aluno")
                        .WithMany("AlunoMaterias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEscolaDeIdiomas.Models.Materia", "Materia")
                        .WithMany("AlunoMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Navigation("AlunoMaterias");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.Navigation("AlunoMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
