// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEscolaDeIdiomas.Models;

#nullable disable

namespace ProjetoEscolaDeIdiomas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241001210633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlunoMatricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Nota")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlunoMatricula");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.HasOne("ProjetoEscolaDeIdiomas.Models.Aluno", null)
                        .WithMany("Materias")
                        .HasForeignKey("AlunoMatricula");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
