// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoEscolaDeIdiomas.Models;

#nullable disable

namespace ProjetoEscolaDeIdiomas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Property<int>("Matricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Matricula");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlunoMatricula")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Inscrito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Nota")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlunoMatricula");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Inscrito = false,
                            Nome = "Portugues",
                            Nota = 0f
                        },
                        new
                        {
                            Id = 2,
                            Inscrito = false,
                            Nome = "Ingles",
                            Nota = 0f
                        },
                        new
                        {
                            Id = 3,
                            Inscrito = false,
                            Nome = "Alemao",
                            Nota = 0f
                        },
                        new
                        {
                            Id = 4,
                            Inscrito = false,
                            Nome = "Frances",
                            Nota = 0f
                        },
                        new
                        {
                            Id = 5,
                            Inscrito = false,
                            Nome = "Japones",
                            Nota = 0f
                        });
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Materia", b =>
                {
                    b.HasOne("ProjetoEscolaDeIdiomas.Models.Aluno", null)
                        .WithMany("Materias")
                        .HasForeignKey("AlunoMatricula");
                });

            modelBuilder.Entity("ProjetoEscolaDeIdiomas.Models.Aluno", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
